
import React, { useState } from 'react';
import { AnalysisResult } from '../types';

interface ResultViewProps {
  result: AnalysisResult;
  t: any;
}

const ResultView: React.FC<ResultViewProps> = ({ result, t }) => {
  const [copied, setCopied] = useState(false);

  const formatContent = (content: string) => {
    return content.split('\n').map((line, i) => {
      if (line.startsWith('# ')) return <h1 key={i} className="text-2xl font-bold text-slate-800 dark:text-slate-100 mt-4 mb-2">{line.replace('# ', '')}</h1>;
      if (line.startsWith('## ')) return <h2 key={i} className="text-xl font-semibold text-slate-800 dark:text-slate-200 mt-4 mb-2">{line.replace('## ', '')}</h2>;
      if (line.startsWith('### ')) return <h3 key={i} className="text-lg font-medium text-slate-800 dark:text-slate-300 mt-3 mb-1">{line.replace('### ', '')}</h3>;
      if (line.trim().startsWith('* ') || line.trim().startsWith('- ')) return <li key={i} className="ml-4 text-slate-600 dark:text-slate-400 mb-1">{line.trim().substring(2)}</li>;
      if (line.trim() === '') return <div key={i} className="h-2" />;
      return <p key={i} className="text-slate-600 dark:text-slate-400 mb-2 leading-relaxed">{line}</p>;
    });
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-emerald-600 bg-emerald-50 border-emerald-200 dark:bg-emerald-900/20 dark:border-emerald-800 dark:text-emerald-400';
    if (score >= 50) return 'text-amber-600 bg-amber-50 border-amber-200 dark:bg-amber-900/20 dark:border-amber-800 dark:text-amber-400';
    return 'text-red-600 bg-red-50 border-red-200 dark:bg-red-900/20 dark:border-red-800 dark:text-red-400';
  };

  const getBarColor = (score: number) => {
    if (score >= 80) return 'bg-emerald-500';
    if (score >= 50) return 'bg-amber-500';
    return 'bg-red-500';
  };

  const handleCopyForDoctor = () => {
    const doctorNote = `
MEDICAL REFERRAL NOTE (Generated by HealthLens AI)
------------------------------------------------
PATIENT ANALYSIS REPORT
Confidence: ${result.confidence.score}% (${result.confidence.label})
------------------------------------------------
DETAILS:
${result.content}
------------------------------------------------
Source Links Provided in App.
    `.trim();
    navigator.clipboard.writeText(doctorNote);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl shadow-lg p-6 border border-slate-100 dark:border-slate-800 animate-in fade-in slide-in-from-bottom-4 duration-500 transition-colors">
      
      {/* Header with Confidence Score */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 border-b border-slate-100 dark:border-slate-800 pb-4 gap-4">
        <div>
          <h2 className="text-xl font-bold text-indigo-900 dark:text-indigo-100 flex items-center">
            <svg className="w-6 h-6 mr-2 text-indigo-600 dark:text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            {t.analysisReport}
          </h2>
          <span className="text-xs text-slate-400 mt-1 block">Language: {result.language}</span>
        </div>

        <div className={`flex flex-col items-end px-4 py-2 rounded-lg border ${getScoreColor(result.confidence.score)}`}>
           <div className="flex items-center space-x-2">
             <span className="text-xs font-bold uppercase tracking-wider">{t.confidenceScore}</span>
             <span className="text-lg font-black">{result.confidence.score}%</span>
           </div>
           <div className="w-full bg-gray-200 dark:bg-slate-700 rounded-full h-1.5 mt-1 min-w-[100px]">
              <div className={`h-1.5 rounded-full ${getBarColor(result.confidence.score)}`} style={{ width: `${result.confidence.score}%` }}></div>
           </div>
           <span className="text-[10px] font-semibold mt-1 uppercase opacity-80">{result.confidence.label} Confidence</span>
        </div>
      </div>

      <div className="prose prose-slate dark:prose-invert max-w-none mb-8">
        {formatContent(result.content)}
      </div>

      {result.sources.length > 0 && (
        <div className="mt-8 pt-6 border-t border-slate-100 dark:border-slate-800">
          <h3 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-4">{t.verificationSources}</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {result.sources.map((source, idx) => (
              <a 
                key={idx} 
                href={source.uri} 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center p-3 bg-slate-50 dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 hover:border-indigo-300 dark:hover:border-indigo-500 hover:bg-white dark:hover:bg-slate-800 transition-all group"
              >
                <div className="bg-indigo-100 dark:bg-indigo-900/50 p-2 rounded mr-3 text-indigo-600 dark:text-indigo-300 group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                </div>
                <div className="overflow-hidden">
                  <p className="text-sm font-medium text-slate-700 dark:text-slate-200 truncate">{source.title}</p>
                  <p className="text-xs text-slate-400 truncate">{new URL(source.uri).hostname}</p>
                </div>
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Doctor in Loop / Professional Review Section */}
      <div className="mt-8 bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-900/30 rounded-xl p-5">
         <div className="flex items-start">
            <div className="bg-blue-100 dark:bg-blue-900/50 p-2 rounded-lg mr-4 text-blue-600 dark:text-blue-300">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                 <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            </div>
            <div className="flex-1">
               <h3 className="text-base font-bold text-blue-900 dark:text-blue-100">{t.consultDoctor}</h3>
               <p className="text-sm text-blue-800 dark:text-blue-300 mt-1 mb-4">
                 {t.consultText}
               </p>
               <div className="flex flex-wrap gap-3">
                 <button 
                   onClick={handleCopyForDoctor}
                   className="px-4 py-2 bg-white dark:bg-slate-800 border border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-200 text-sm font-medium rounded-lg hover:bg-blue-50 dark:hover:bg-slate-700 transition-colors flex items-center"
                 >
                   {copied ? (
                     <>
                        <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                        Copied
                     </>
                   ) : (
                     <>
                        <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                        {t.copyReferral}
                     </>
                   )}
                 </button>
                 <button 
                   onClick={() => document.getElementById('doctor-finder')?.scrollIntoView({ behavior: 'smooth' })}
                   className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition-colors flex items-center shadow-sm"
                 >
                   {t.findDoctor}
                   <svg className="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" /></svg>
                 </button>
               </div>
            </div>
         </div>
      </div>

    </div>
  );
};

export default ResultView;
